project:
  type: website

website:
  title: "Creating the World"
  navbar:
    right:
      - href: Sites/Overview.qmd
        text: "Kursübersicht"
        icon: calendar-range
      - text: "Cheatsheets" 
        icon: lightbulb
        menu:
          - href: Cheatsheets/cheatsheet_keys.pdf
            text: "Tastenkombinationen"
          - href: Cheatsheets/cheatsheet_shading.pdf
            text: "Shading"
      - text: Ressourcen
        icon: folder
      - text: "Folien"
        icon: images
      - text: "Skript"
        icon: eyeglasses
        menu:
          - href: Chapters/Chapter_1.qmd
            text: Kapitel 1
          - href: Chapters/Chapter_2.qmd
            text: Kapitel 2
          - href: Chapters/Chapter_3.qmd
            text: Kapitel 3
      - href: about.qmd
        icon: info-circle
        text: Über

format:
  html:
    theme: [cosmos, styles.scss]
    toc: true
    toc-title: Auf dieser Seite
    fontsize: 17px
    lang: de