project:
  type: website

website:
  title: "Creating the World"
  navbar:
    right:
      - text: "Kapitel"  
        menu:
          - href: Chapters/Chapter_1.qmd
            text: Kapitel 1
          - href: Chapters/Chapter_2.qmd
            text: Kapitel 2
      - text: "Folien"
        menu: 
          - href: Chapters/Chapter_1.qmd
            text: Kapitel 1
      - text: "Ressourcen"
        menu:
          - href: Chapters/Chapter_1.qmd
            text: Kapitel 1
      - href: about.qmd
        text: Über


format:
  html:
    theme: journal
    css: styles.css
    toc: true



