project:
  type: website
  output-dir: docs

website:
  title: "Creating the World"
  page-navigation: true
  reader-mode: true
  bread-crumbs: false
  navbar:
    right:
      - href: Sites/Overview.qmd
        text: "Kursübersicht"
        icon: calendar-range
      - text: "Cheatsheets" 
        icon: lightbulb
        menu:
          - href: Cheatsheets/cheatsheet_keys.pdf
            text: "Tastenkombinationen"
          - href: Cheatsheets/cheatsheet_shading.pdf
            text: "Shading"
      - text: Ressourcen
        icon: folder
        menu: 
          - href: assets/Blender_Files/01_Demofile.zip
            text: "Demofile" 
          - href: assets/Blender_Files/03_Bildvorlage.zip
            text: "Bildvorlage"             
          - href: assets/Blender_Files/03_Haus.zip
            text: "Haus" 
          - href: assets/Blender_Files/04_Glas_Querschnitt.zip
            text: "Glas-Querschnitt"
          - href: assets/Blender_Files/05_Uebung_12_1.zip
            text: "Übung 12.1" 
          - href: assets/Blender_Files/05_Uebung_13_1.zip
            text: "Übung 13.1" 
          - href: assets/Blender_Files/06_Hammer.zip
            text: "Hammer" 
          - href: assets/Blender_Files/07_Beispiel_Glas_Material.zip
            text: "Glasmaterial"
          - href: assets/Blender_Files/07_Displacement_Map.zip
            text: "Displacement Map" 
          - href: assets/Blender_Files/08_Dunes.zip
            text: "Dünen" 
          - href: assets/Blender_Files/08_Gameboard_Lights.zip
            text: "Spielbrett" 
          - href: assets/Blender_Files/09_Glas_Particles.zip
            text: "Glaspartikel"
          - href: assets/Blender_Files/10_Baum.zip
            text: "Baum"
          - href: assets/Blender_Files/10_Cat_Character.zip
            text: "Katze-Charakter"
          - href: assets/Blender_Files/11_Alien.zip
            text: "Alien"
          - href: assets/Blender_Files/11_Character.zip
            text: "Charakter"
          - href: assets/Blender_Files/11_Schwimmnudel.zip
            text: "Schwimmnudel"
          - href: assets/Blender_Files/12_Pendel.zip
            text: "Pendel"
          - href: assets/Blender_Files/Leistungsnachweis_5_Raum.zip
            text: "Leistungsnachweis"
          - href: assets/Blender_Files/13_Erde.zip
            text: "Erde"
          - href: assets/Blender_Files/13_Human.zip
            text: "Human"
          - href: assets/Blender_Files/14_Freestyle.zip
            text: "Freestyle"
      - text: "Folien"
        menu: 
          - href: Slides/Slides_00_Organisatorisches.pdf
            text: "0. Organisatorisches"
          - href: Slides/Slides_01_Einfuehrung.pdf
            text: "1. Einführung"
          - href: Slides/Slides_02_Objekterstellung.pdf
            text: "2. Objekterstellung"
          - href: Slides/Slides_04_Modifiers.pdf
            text: "4. Modifiers"
          - href: Slides/Slides_05_Materialien.pdf
            text: "5. Materialien"
          - href: Slides/Slides_06_Texturen.pdf
            text: "6. Texturen"
          - href: Slides/Slides_07_BSDF.pdf
            text: "7. Principled-BSDF-Shader"
          - href: Slides/Slides_08_Licht_Welten.pdf
            text: "8. Licht & Welten"
          - href: Slides/Slides_10_Charaktererstellung.pdf
            text: "10. Charaktererstellung"
          - href: Slides/Slides_13_Animation_VR.pdf
            text: "13. Animation in Virtual-Realität"
          - href: Slides/Slides_14_Linien.pdf
            text: "14. Linien"
          - href: Slides/Slides_Abgabe_1.pdf
            text: "Abgabe 1"
          - href: Slides/Slides_Abgabe_2.pdf
            text: "Abgabe 2"            
          - href: Slides/Slides_Abgabe_3.pdf
            text: "Abgabe 3"
          - href: Slides/Slides_Abgabe_4.pdf
            text: "Abgabe 4"
          - href: Slides/Slides_Abgabe_5.pdf
            text: "Abgabe 5"
          - href: Slides/Slides_Abgabe_6.pdf
            text: "Abgabe 6"            
        icon: images
      - text: "Skript"
        icon: eyeglasses
        href: Sites/chapter_overview.qmd
        # menu:
        #   - href: Chapters/Chapter_1.qmd
        #     text: Kapitel 1
        #   - href: Chapters/Chapter_2.qmd
        #     text: Kapitel 2
        #   - href: Chapters/Chapter_3.qmd
        #     text: Kapitel 3
        #   - href: Chapters/Chapter_4.qmd
        #     text: Kapitel 4
        #   - href: Chapters/Chapter_5.qmd
        #     text: Kapitel 5
        #   - href: Chapters/Chapter_6.qmd
        #     text: Kapitel 6
        #   - href: Chapters/Chapter_7.qmd
        #     text: Kapitel 7
        #   - href: Chapters/Chapter_8.qmd
        #     text: Kapitel 8
        #   - href: Chapters/Chapter_9.qmd
        #     text: Kapitel 9
        #   - href: Chapters/Chapter_10.qmd
        #     text: Kapitel 10
        #   - href: Chapters/Chapter_11.qmd
        #     text: Kapitel 11
        #   - href: Chapters/Chapter_12.qmd
        #     text: Kapitel 12
        #   - href: Chapters/Chapter_13.qmd
        #     text: Kapitel 13
        #   - href: Chapters/Chapter_14.qmd
        #     text: Kapitel 14
        #   - href: Chapters/Chapter_15.qmd
        #     text: Kapitel 15
        #   - href: Chapters/Chapter_16.qmd
        #     text: Kapitel 16
        #   - href: Chapters/Chapter_17.qmd
        #     text: Kapitel 17
        #   - href: Chapters/Chapter_18.qmd
        #     text: Kapitel 18 
        #   - href: Chapters/Chapter_19.qmd
        #     text: Kapitel 19
        #   - href: Chapters/Chapter_20.qmd
        #     text: Kapitel 20
        #   - href: Chapters/Chapter_21.qmd
        #     text: Kapitel 21
        #   - href: Chapters/Chapter_22.qmd
        #     text: Kapitel 22
        #   - href: Chapters/Chapter_23.qmd
        #     text: Kapitel 23
        #   - href: Chapters/Chapter_24.qmd
        #     text: Kapitel 24
        #   - href: Chapters/Chapter_25.qmd
        #     text: Kapitel 25
        #   - href: Chapters/Chapter_25.qmd
        #     text: Kapitel 25
        #   - href: Chapters/Chapter_26.qmd
        #     text: Kapitel 26
        #   - href: Chapters/Chapter_27.qmd
        #     text: Kapitel 27
        #   - href: Chapters/Chapter_28.qmd
        #     text: Kapitel 28
        #   - href: Chapters/Chapter_29.qmd
        #     text: Kapitel 29
        #   - href: Chapters/Chapter_30.qmd
        #     text: Kapitel 30
        #   - href: Chapters/Chapter_31.qmd
        #     text: Kapitel 31
        #   - href: Chapters/Chapter_32.qmd
        #     text: Kapitel 32
        #   - href: Chapters/Chapter_33.qmd
        #     text: Kapitel 33
        #   - href: Chapters/Chapter_34.qmd
        #     text: Kapitel 34
        #   - href: Chapters/Chapter_35.qmd
        #     text: Kapitel 35
        #   - href: Chapters/Chapter_36.qmd
        #     text: Kapitel 36
        #   - href: Chapters/Chapter_37.qmd
        #     text: Kapitel 37
        #   - href: Chapters/Chapter_38.qmd
        #     text: Kapitel 38 
        #   - href: Chapters/Chapter_39.qmd
        #     text: Kapitel 39
        #   - href: Chapters/Chapter_40.qmd
        #     text: Kapitel 40
        #   - href: Chapters/Chapter_41.qmd
        #     text: Kapitel 41
        #   - href: Chapters/Chapter_42.qmd
        #     text: Kapitel 42
        #   - href: Chapters/Chapter_43.qmd
        #     text: Kapitel 43
        #   - href: Chapters/Chapter_44.qmd
        #     text: Kapitel 44
        #   - href: Chapters/Chapter_45.qmd
        #     text: Kapitel 45
        #   - href: Chapters/Chapter_46.qmd
        #     text: Kapitel 46
        #   - href: Chapters/Chapter_47.qmd
        #     text: Kapitel 47
        #   - href: Chapters/Chapter_48.qmd
        #     text: Kapitel 48
        #   - href: Chapters/Chapter_49.qmd
        #     text: Kapitel 49
      - href: about.qmd
        icon: info-circle
        text: Über
  sidebar:
    - id: skript
      title: "Skript"
      style: docked
      collapse-level: 1
      contents:  
        - href: Sites/chapter_overview.qmd
          text: "Kapitelübersicht"
        - section: "Kapitel"
          contents:          
            - href: Chapters/Chapter_1.qmd
              text: Kapitel 1
            - href: Chapters/Chapter_2.qmd
              text: Kapitel 2
            - href: Chapters/Chapter_3.qmd
              text: Kapitel 3
            - href: Chapters/Chapter_4.qmd
              text: Kapitel 4
            - href: Chapters/Chapter_5.qmd
              text: Kapitel 5
            - href: Chapters/Chapter_6.qmd
              text: Kapitel 6
            - href: Chapters/Chapter_7.qmd
              text: Kapitel 7
            - href: Chapters/Chapter_8.qmd
              text: Kapitel 8
            - href: Chapters/Chapter_9.qmd
              text: Kapitel 9
            - href: Chapters/Chapter_10.qmd
              text: Kapitel 10
            - href: Chapters/Chapter_11.qmd
              text: Kapitel 11
            - href: Chapters/Chapter_12.qmd
              text: Kapitel 12
            - href: Chapters/Chapter_13.qmd
              text: Kapitel 13
            - href: Chapters/Chapter_14.qmd
              text: Kapitel 14
            - href: Chapters/Chapter_15.qmd
              text: Kapitel 15
            - href: Chapters/Chapter_16.qmd
              text: Kapitel 16
            - href: Chapters/Chapter_17.qmd
              text: Kapitel 17
            - href: Chapters/Chapter_18.qmd
              text: Kapitel 18
            - href: Chapters/Chapter_19.qmd
              text: Kapitel 19
            - href: Chapters/Chapter_20.qmd
              text: Kapitel 20
            - href: Chapters/Chapter_21.qmd
              text: Kapitel 21
            - href: Chapters/Chapter_22.qmd
              text: Kapitel 22
            - href: Chapters/Chapter_23.qmd
              text: Kapitel 23
            - href: Chapters/Chapter_24.qmd
              text: Kapitel 24
            - href: Chapters/Chapter_25.qmd
              text: Kapitel 25
            - href: Chapters/Chapter_25.qmd
              text: Kapitel 25
            - href: Chapters/Chapter_26.qmd
              text: Kapitel 26
            - href: Chapters/Chapter_27.qmd
              text: Kapitel 27
            - href: Chapters/Chapter_28.qmd
              text: Kapitel 28
            - href: Chapters/Chapter_29.qmd
              text: Kapitel 29
            - href: Chapters/Chapter_30.qmd
              text: Kapitel 30
            - href: Chapters/Chapter_31.qmd
              text: Kapitel 31
            - href: Chapters/Chapter_32.qmd
              text: Kapitel 32
            - href: Chapters/Chapter_33.qmd
              text: Kapitel 33
            - href: Chapters/Chapter_34.qmd
              text: Kapitel 34
            - href: Chapters/Chapter_35.qmd
              text: Kapitel 35
            - href: Chapters/Chapter_36.qmd
              text: Kapitel 36
            - href: Chapters/Chapter_37.qmd
              text: Kapitel 37
            - href: Chapters/Chapter_38.qmd
              text: Kapitel 38
            - href: Chapters/Chapter_39.qmd
              text: Kapitel 39
            - href: Chapters/Chapter_40.qmd
              text: Kapitel 40
            - href: Chapters/Chapter_41.qmd
              text: Kapitel 41
            - href: Chapters/Chapter_42.qmd
              text: Kapitel 42
            - href: Chapters/Chapter_43.qmd
              text: Kapitel 43
            - href: Chapters/Chapter_44.qmd
              text: Kapitel 44
            - href: Chapters/Chapter_45.qmd
              text: Kapitel 45
            - href: Chapters/Chapter_46.qmd
              text: Kapitel 46
            - href: Chapters/Chapter_47.qmd
              text: Kapitel 47
            - href: Chapters/Chapter_48.qmd
              text: Kapitel 48
            - href: Chapters/Chapter_49.qmd
              text: Kapitel 49
format:
  html:
    theme: [cosmos, assets/css/style.scss]
    toc: true
    toc-title: Auf dieser Seite
    fontsize: 17px
    lang: de