---
title: "10. Einstieg in den Edit-Mode"
editor: visual
---

Ein Grossteil der Bearbeitungsmöglichkeiten, welche im Object-Mode mit Objekten möglich sind, kann im Edit-Mode auch auf die Strukturelemente der Objekte angewendet werden.

## Grab, Scale, Rotate

::: column-margin
Ein Vertex kann nur bewegt werden
:::

Wenn ein einzelner Vertex ausgewählt wird, sind die Transformationsmöglichkeiten relativ beschränkt. Mittels der Taste {{< kbd G >}} lässt sich der Vertex im dreidimensionalen Raum verschieben. Da der Vertex allerdings nur einen isolierten Punkt ohne eine Dimension darstellt, kann er weder skaliert, noch rotiert werden. Dementsprechend wird in der Sidebar lediglich die Position des Vertex angegeben, während die Skalierung und Rotation – anders als im Object-Mode – nicht angegeben werden.

::: column-margin
Skalierung und Rotation geschieht um den Median der Auswahl
:::

Sobald zwei Vertices ausgewählt werden, wird in der Sidebar nicht mehr die Position der einzelnen Vertices angegeben, sondern die Position des Medians zwischen diesen beiden Vertices. Dies ist unabhängig davon, ob die Vertices mittels Edges oder Faces miteinander verbunden sind oder nicht. Mittels der Taste {{< kbd R >}} oder {{< kbd S >}} kann die Auswahl rotiert oder skaliert werden. Beide Transformationen beziehen sich dabei auf den Median zwischen diesen beiden Vertices. Wird also beispielsweise eine Skalierung um den Faktor 2 getätigt (mittels der Tasten {{< kbd S >}} und {{< kbd 2 >}}), verdoppelt sich der Abstand der beiden Vertices zum Median. Rotationen führen dazu, dass die Vertices ebenfalls um den Median rotiert werden.

::: column-margin
Skalierung und Rotation verändert Position von Vertices
:::

Dadurch lässt sich bereits ein wichtiges Merkmal der Bearbeitung im Edit-Mode betrachten: Mittels einer Skalierung lässt sich die Distanz zwischen zwei Vertices verändern und dadurch auch ihre Position. Ebenso werden Vertices bei der Rotation relativ zueinander im Raum rotiert und so in ihren Positionen verändert. Dies macht auch einen Abschnitt für die Skalierung oder Rotation in der Sidebar obsolet, da jegliche Transformation lediglich zu einer Veränderung der individuellen Platzierung der Vertices führt.

Anstatt der Vertices können auch Edges und Faces direkt angewählt werden. Dabei werden automatisch die dazugehörigen Vertices mit ausgewählt. Die Transformationen beziehen sich immer noch auf den räumlichen Mittelpunkt zwischen den einzelnen Vertices, weshalb auch in diesem Modus eine Skalierung oder Rotation zu einer Veränderung der Positionen dieser Vertices führen.

:::::: rememberbox
:::: rememberbox-header
::: rememberbox-icon
:::

Merke...
::::

::: rememberbox-body
Wie auch im Object-Mode können Vertices, Edges und Faces mittels der Taste {{< kbd G >}} bewegt, mittels der Taste {{< kbd S >}} und mittels der Taste {{< kbd R >}} rotiert werden.

Skalierungen und Rotationen im Edit-Mode führen lediglich zu einer Veränderung der Positionen der einzelnen Vertices basierend auf dem Median der Vertex-Positionen.
:::
::::::

## Add, Delete, Dissolve

::: column-margin
Primitives innerhalb eines Objektes hinzufügen
:::

Innerhalb eines Objektes im Edit-Mode können weitere Mesh-Primitives hinzugefügt werden. Dies geschieht wie im Object-Mode mit der Tastenkombination {{< kbd Shift >}} + {{< kbd A >}}. Die Auswahl ist allerdings nur noch auf Mesh-Primitives beschränkt. Dementsprechend ist es nicht möglich, einem Mesh im Edit-Mode ein Kurven-Objekt anzufügen. Allerdings stehen alle primitiven Formen der Meshes zur Verfügung. Wie auch im Object-Mode werden die Objekte an der Position des 3D-Cursors hinzugefügt.

::: column-margin
Elemente löschen mit {{< kbd X >}}
:::

Wie auch im Object-Mode können im Edit-Mode ausgewählte Elemente gelöscht werden, indem die Taste {{< kbd X >}} oder {{< kbd Delete >}} gedrückt wird. Anders als im Object-Mode erscheint bei beiden Tasten ein Menü beim Mauszeiger, allerdings weil in diesem Fall der Löschvorgang präzisiert werden muss. So lassen sich jeweils die ausgewählten Faces, die ausgewählten Edges oder die ausgewählten Vertices löschen.

::: column-margin
Elemente, welche beim Löschen eben falls entfernt werden
:::

Wird etwa beim Default-Cube eine einzelne Fläche ausgewählt und das Face gelöscht, so bleiben die Edges, welche sich um die Fläche bilden, erhalten – lediglich das ausgewählte Face wird gelöscht. Wenn allerdings die Edges gelöscht werden, verschwinden alle Edges, welche das ausgewählte Face bilden – lediglich die Vertices bleiben bestehen. Durch die fehlenden Edges verschwinden nun allerdings auch die angrenzenden Faces, da diesen nun je ein Edge fehlt. Wenn stattdessen die Vertices gelöscht werden, fehlen auch für die angrenzenden Edges die Bezugspunkte. Als Folge bleibt nur noch die gegenüberliegende Fläche bestehen.

::: column-margin
Faces und Edges isoliert löschen
:::

Bei der Auswahl von mehreren Flächen oder Edges kann das Löschen von Elementen zu grösseren Veränderungen führen. So werden beim Löschen von mehreren aneinandergereihten Faces auch die Edges, welche die Faces abgrenzen, gelöscht. Um dies zu verhindern kann beim Löschen die Option «*Only Faces*» ausgewählt werden. Dadurch bleiben die Edges bestehen. Zudem gibt es die Option «*Only Edges & Faces*» um lediglich die einzelnen Vertices zu erhalten.

::: column-margin
Elemente auflösen
:::

Nebst dem Löschen von Elementen besteht auch die Auswahl, dass Elemente aufgelöst werden. Hierfür wird die Option «*Dissolve*» im Lösch-Menü angeboten. Dadurch werden die ausgewählten Elemente gelöscht und die benachbarten Elemente anschliessend verbunden. Wird ein einzelnes Edge ausgewählt, welches zwischen zwei Faces liegt, werden die beiden Faces durch das Auflösen zu einem Face kombiniert. Ähnlich verhält es sich beim Auflösen von Faces und Vertices.

## Duplicate

::: column-margin
Duplizieren mittels {{< kbd D >}}
:::

Auch im Edit-Mode können Elemente mittels der Taste dupliziert werden, wenn sie vorgängig ausgewählt wurden. Nach dem Tastendruck ist es direkt möglich, die Objekte zu bewegen und mittels der linken Maustaste, {{< kbd Enter >}}- oder {{< kbd Space >}}-Taste zu platzieren. Mittels der Taste {{< kbd esc >}} oder der rechten Maustaste kann diese Bewegung abgebrochen werden und das Objekt wird an seine ursprüngliche Position zurückgesetzt. Dadurch ist allerdings oftmals nicht mehr ersichtlich, dass sich ein Duplikat an der Stelle des Originals befindet. Deshalb ist es sinnvoll, in einem solchen Fall die letzte Aktion – also das Duplizieren – ruckgängig zu machen oder das Duplikat direkt zu löschen. Empfehlenswert ist es auch, die Elemente trotzdem an einer anderen Stelle zu platzieren und sie dann erst zu löschen. Dadurch lässt sich erkennen, dass die Elemente dupliziert wurden und noch gelöscht werden müssen.

## Globale vs. lokale Koordinaten

::: column-margin
Globale Koordinaten
:::

Im Edit-Mode gibt es zwei Arten von 3D-Koordinaten, mit denen die Position eines Vertex – respektive der Median der Auswahl mehrerer Vertices – angegeben wird: die globalen und die lokalen Koordinaten. Die globalen Koordinaten entsprechen denselben Koordinaten, die auch im Object Mode verwendet werden. Diese beziehen sich auf den Ursprung der Welt, welcher sich an der Position 0 aller drei Achsen befindet. Dabei handelt es sich auch um den Punkt, an dem sich die Achsen im 3D-Viewport kreuzen.

::: column-margin
Lokale Koordinaten
:::

Die lokalen Koordinaten beziehen sich jeweils auf die Koordinaten des aktuellen Objektes. Das heisst, dass diese Koordinaten sich immer auf den Ursprung des Objektes beziehen. Wenn sich der Ursprung des Objektes am Nullpunkt aller drei Achsen befindet und keine Skalierung oder Rotation auf das Objekt angewendet wird, dann sind die globalen und die lokalen Koordinaten identisch. Wenn sich der Ursprung allerdings an einer anderen Stelle im Raum befindet, beziehen sich die lokalen Koordinaten immer auf den Ursprung des Objektes als Nullpunkt.

::: column-margin
Skalierung und Rotation des Objekts sind unabhängig vom Edit-Mode
:::

Zudem bleiben die lokalen Koordinaten auch unangetastet von Skalierungen und Rotationen, welche im Object-Mode für ein Objekt angegeben wurden. Wird der Default-Cube im Object-Mode gedreht, verändert sich die Position der Vertices also in den globalen Koordinaten, allerdings nicht in den lokalen Koordinaten.

:::::: exercisebox
:::: exercisebox-header
::: exercisebox-icon
:::

Übung 5: Edit-Mode
::::

::: exercisebox-body
**Übung 5.1**

Verändern Sie den Default-Cube so, dass die Position der einzelnen Vertices in der globalen Koordinate gegenüber der lokalen Koordinate doppelt so hohe absolute Beträge aufweisen.

**Übung 5.2**

Verändern Sie den Default-Cube so, dass sich sein Ursprung nicht mehr in der Mitte seines Volumens befindet, sondern in der Mitte seiner unteren Fläche.
:::
::::::
