---
title: "4. Erste Schritte "
editor: visual
---

## Die Default-Szene

::: column-margin
Objekte in der Default-Szene
:::

Beim Start eins neuen Projekts erscheint eine Default-Szene. Diese Szene beinhaltet bereits die wesentlichen Dinge, welche für eine 3D-Szene benötigt werden:

-   **Würfel**: Genau in der Mitte der Szene befindet sich der Default-Cube. Bei diesem Würfel handelt es sich um ein 3D-Objekt. Er hat eine Grösse von 2x2x2 Metern.
-   **Kamera**: Von der Kamera aus wird eine Szene nach deren Verarbeitung (z.B. in einem geren derten Bild oder einem Video) betrachtet. In der Default-Szene ist die Kamera auf den Würfel gerichtet.
-   **Lichtquelle**: Die Lichtquelle wird dafür benötigt, dass der Würfel in der gerenderten Aufnahme beleuchtet wird. Ohne eine Lichtquelle sind die 3D-Objekte beim anschliessenden Rendern nicht sichtbar – es sei denn, sie stellen selbst eine Lichtquelle dar.

:::::: tippbox
:::: tippbox-header
::: tippbox-icon
:::
Weiterführende Informationen
::::

::: tippbox-body
Die Default-Szene kann manuell angepasst werden. Hierfür muss zunächst eine Default-Szene erstellt werden, welche bei jedem Start erscheinen soll. Diese kann dann unter «*File* \| *Defaults* \| *Save Startup File*» als neue Start-up Szene gespeichert werden.
:::
::::::

## Auswahl von Objekten

::: column-margin
Auswahl und Abwahl mittels Mausklick
:::

Durch das Anklicken mittels der linken Maustaste können Objekte im 3D-Viewport ausgewählt werden. Die ausgewählten Objekte sind anschliessend anhand einer farblichen Markierung erkennbar. Durch das Klicken in den leeren Raum des Viewport-Displays lassen sich die Objekte wieder abwählen. Zudem wird durch die Auswahl eines anderen Objektes das vorher ausgewählte Objekt abgewählt.

::: column-margin
Mehrfachwahl mittels {{< kbd Shift >}}
:::

Um mehrere Objekte gleichzeitig auszuwählen, gibt es verschiedene Möglichkeiten. Eine Möglichkeit besteht darin, dass nacheinander Objekte bei gedrückter {{< kbd Shift >}}-Taste angeklickt und so zur Auswahl hinzugefügt werden. Durch die Auswahl von mehreren Objekten wird das zuletzt ausgewählt Objekt mit einer orangen und die vorherig ausgewählten Objekte mittels einer roten Farbe markiert.

::: column-margin
Aktives Objekt
:::

Die Markierung mit einer orangen Farbe gibt jeweils an, dass es sich bei diesem Objekt um das aktive Objekt handelt. Diese Unterscheidung wird in späteren Kapiteln noch von Bedeutung sein, etwa wenn Merkmale vom aktiven Objekt auf andere Objekte übertragen werden sollen, oder wenn ein Objekt in Bezug zum aktiven Objekt verändert werden soll. Für den aktuellen Stand ist jedoch vor allem wichtig, wie die Objekte ausgewählt werden, und hierfür macht die rote oder orange Markierung noch keinen Unterschied aus.

::: column-margin
Box-Selection mittels {{< kbd B >}}
:::

Alternativ kann auf den Box-Select-Modus zurückgegriffen werden. Dieser wird mit der {{< kbd B >}} Taste aktiviert. Durch das Gedrückthalten der linken Maustaste lässt sich anschliessend ein Viereck über den Bildschirm ziehen. Alle Objekte, welche sich anschliessend innerhalb dieser Box befinden, werden nach dem Loslassen der linken Maustaste ausgewählt. Mittels der Taste {{< kbd esc >}} oder der rechten Maustaste lässt sich die Box-Selection abbrechen.

::: column-margin
Circle-Selection mittels {{< kbd C >}}
:::

Alternativ können Objekte auch mit dem Circle-Select-Modus ausgewählt werden. Der Circle-Select Modus wird mit der Taste {{< kbd C >}} aktiviert. Bei der Verwendung des Circle-Select-Modus ist der Mauszeiger von einem Kreis umgeben. Mithilfe des Mausrads kann die Grösse des Kreises eingestellt werden. Durch einen Klick mit der linken Maustaste werden die Objekte, welche sich innerhalb dieses Kreises befinden, alle ausgewählt. Durch das Bewegen des Mauszeigers bei gedrückter linken Maustaste können so eine Reihe weiterer Objekte ausgewählt werden. Der Circle-Select-Modus muss allerdings aktiv beendet werden, da ein weiterer Klick mit der linken Maustaste zu einer weiteren Auswahl von Objekten führt. Um den Circle-Select-Modus wieder zu verlassen, kann die Taste {{< kbd Enter >}}, {{< kbd esc >}} oder der rechten Maustaste gedrückt werden. Anschliessend sind alle Objekte, welche im Circle-Select-Modus angeklickt wurden, ausgewählt.

::: column-margin
Auswahl umkehren
:::

Mittels der Tastenkombination {{< kbd Ctrl >}} + {{< kbd I >}} ist es möglich, die Auswahl umzukehren. Dadurch werden alle ausgewählten Objekte abgewählt und alle anderen Objekte ausgewählt. Wenn alle Objekte innerhalb einer Szene ausgewählt werden sollen, kann die Taste {{< kbd A >}} gedrückt werden. Dadurch werden auch Objekte, die möglicherweise ausserhalb des gerade sichtbaren Bereichs liegen, ausgewählt.

::: column-margin
Auswahl von Objekten im Outliner
:::

Im Outliner auf der rechten Seite wird mittels einer blauen Markierung angezeigt, welches Objekt gerade ausgewählt ist. Zudem lassen sich auch hier Objekte auswählen, indem sie mittels der linken Maustaste angeklickt werden. Die Auswahl von mehreren Objekten kann analog wie im Viewport-Display mittels des Gedrückthaltens der {{< kbd Shift >}}-Taste getroffen werden oder durch eine Box-Auswahl mittels der Taste {{< kbd B >}} . Auch hier können alle Objekte mittels der Taste {{< kbd A >}} gemeinsam ausgewählt werden. Der Circle-Select-Modus funktioniert allerdings nicht im Outliner.

## Hinzufügen von Objekten

::: column-margin
Hinzufügen von Objekten mittels {{< kbd Shift >}} + {{< kbd A >}}
:::

Mittels der Tastenkombination {{< kbd Shift >}} + {{< kbd A >}} erscheint beim Mauszeiger das Menü-Feld «*Add*». Dabei handelt es sich um dasselbe Menü-Feld, welches auch unter dem Reiter «*Add*» in der linken oberen Ecke aufgerufen werden kann. Mithilfe dieses Menü-Felds können eine Reihe von verschiedenen Objekten im Viewport Display hinzugefügt werden. Es gibt eine Reihe verschiedener Objektarten, welche hinzugefügt werden können. Beispielsweise kann unter «*Mesh* \| *Cube*» ein Würfel in die Szene hinzugefügt werden. Ein neues Objekt wird jeweils an der Position des 3D-Cursors eingefügt.

::: column-margin
Neue Objekte anpassen
:::

Wenn ein neues Objekt hinzugefügt wird, wird dieses Objekt direkt angewählt und farblich markiert. Zudem erscheint in der unteren linken Ecke des Viewport-Displays ein Kontext-Menü-Feld. Dieses Menü-Feld kann aufgeklappt werden und beinhaltet Einstellungen zum Objekt, welche noch spezifiziert werden können. Beim Hinzufügen eines Würfels besteht etwa die Möglichkeit, dass man dessen Grösse (Size), seine Position und seine Rotation entlang der X-, Y- und Z-Achse anpassen kann. Da das Objekt jeweils an der Stelle des 3D-Cursors erscheint, entspricht die Position des Objektes in diesem Menü jeweils auch der Position des 3D-Cursors.

::: column-margin
Kontext-Menü zum neuen Objekt
:::

Das Kontext-Menü, welches beim Hinzufügen von Objekten erscheint, ist nur temporär vorhanden. Sobald mit der linken Maustaste in einen Bereich ausserhalb des Kontext-Menüs geklickt wird, verschwindet das Menü-Feld. Es gibt keine Möglichkeit, dieses Menü-Feld zurückzuholen – es ist für immer für dieses Objekt verschwunden. Wenn das Menü nochmals benötigt werden sollte, muss das entsprechende Objekt erneut zur Szene hinzugefügt werden.

:::::: rememberbox
:::: rememberbox-header
::: rememberbox-icon
:::

Merke...
::::

::: rememberbox-body
Kontext-Menü-Felder erscheinen in der linken unteren Ecke des Viewport-Displays und sind nur temporär verfügbar. Nach einem Klick ausserhalb des Menü-Feldes verschwinden dieses Felder und können nicht mehr zurückgeholt werden.
:::
::::::

## Löschen von Objekten

::: column-margin
Löschen von Objekten mittels {{< kbd X >}}
:::

Wenn ein Objekt gelöscht werden soll, muss dieses zunächst ausgewählt werden. Mittels der Taste {{< kbd X >}} wird der Befehl für die Löschung des ausgewählten Objektes gegeben. Dieser muss anschliessend bestätigt werden, entweder mit einem Mausklick auf das daraufhin beim Mauszeiger erscheinende «*Delete*»-Feld oder mittels der Taste {{< kbd Enter >}}. Alternativ kann auch die Taste {{< kbd Delete >}} verwendet werden – hierbei wird das Objekt direkt gelöscht, ohne dass eine Bestätigung nötig ist.

:::::: exercisebox
:::: exercisebox-header
::: exercisebox-icon
:::

Übung 2: Hinzufügen und Löschen
::::

::: exercisebox-body
**Übung 2.1**

Löschen Sie alle Objekte aus der Szene.

**Übung 2.2**

Erstellen Sie einen neuen Würfel mit der Grösse 1 und einer Rotation von 90°. Welche Achse Sie hierfür wählen, spielt keine Rolle.
:::
::::::

:::::: rememberbox
:::: rememberbox-header
::: rememberbox-icon
:::

Merke...
::::

::: rememberbox-body
Mittels {{< kbd Shift >}} + {{< kbd A >}} erscheint beim Mauszeiger das Menü zum Hinzufügen von Objekten.

Um Objekte zu löschen, müssen sie zunächst ausgewählt werden und können anschliessend mit der Taste {{< kbd X >}} oder {{< kbd Delete >}} gelöscht werden.
:::
::::::

## Objekte vervielfältigen

::: column-margin
Methoden zur Vervielfältigung von Objekten
:::

Ausgewählte Objekte können auf verschiedene Arten dupliziert werden. Jede diese Arten hat ihre eigenen Besonderheiten:

-   Duplizieren des Objektes
-   Verbundene Duplikate erstellen
-   Einfügen einer Kopie des Objektes mittels Copy-Paste

### Objekte duplizieren

::: column-margin
Duplikat eines Objektes erstellen mittels {{< kbd Shift >}} + {{< kbd D >}}
:::

Die schnellste Methode, um Objekte zu duplizieren, besteht darin, dass die entsprechenden Objekte, welche dupliziert werden sollen, ausgewählt werden und anschliessend mit der Tastenkombination {{< kbd Shift >}} + {{< kbd D >}} der Befehl zur Duplikation der Objekte gegeben wird. Dadurch entsteht an der Position des originalen Objekts ein Duplikat, welches mit der Bewegung des Mauszeigers im Raum bewegt werden kann. Durch einen Klick mit der linken Maustaste, {{< kbd Space >}}- oder {{< kbd Enter >}}-Taste wird das Objekt anschliessend platziert. Die Bewegung des duplizierten Objekts kann auch mittels abgebrochen werden. Dadurch wird das Duplikat allerdings nicht gelöscht, sondern an derselben Position wie das Original platziert.

### Verbundene Duplikate erstellen

::: column-margin
Verbundene Duplikate erstellen mittels {{< kbd Alt >}} + {{< kbd D >}}
:::

Nebst einem normalen Duplikat kann auch ein verbundenes Duplikat erstellt werden. Hierfür wird nach der Auswahl der zu duplizierenden Objekte die Tastenkombination {{< kbd Alt >}} + {{< kbd D >}} gedrückt. Auch bei dieser Methode kann das Objekt mit der Maus im Raum bewegt und mittels der linken Maustaste oder {{< kbd Enter >}}Taste platziert werden. Wird nun in weiteren Arbeitsschritten entweder das originale oder das verbunden duplizierte Objekt bearbeitet, führt dies dazu, dass dieselben Veränderungen gleichzeitig auch bei allen verbundenen Objekten durchgeführt werden.

### Copy-Paste von Objekten

::: column-margin
Objekte mittels Copy-Paste vervielfältigen
:::

Eine weitere Methode zur Vervielfältigung von Objekten besteht darin, dass die zu vervielfältigenden Objekte ausgewählt und mittels {{< kbd Ctrl >}} + {{< kbd C >}} kopiert und anschliessend mittels {{< kbd Ctrl >}} + {{< kbd V >}} wieder eingefügt werden. Im Gegensatz zur normalen und zur verbundenen Duplizierung werden die eingefügten Objekte direkt platziert und müssen durch weitere Befehle verschoben werden. Zudem werden bei dieser Methode auch von den Materialien des Objektes eine Kopie erstellt, welche dann dem neu eingefügten Objekt zugewiesen wird. Dadurch führt eine Bearbeitung des Materials des originalen Objekts nicht zu einer Veränderung des Materials des neu eingefügten Objekts. Allerdings kann dem eingefügten Objekt auch wieder das originale Material zugewiesen werden.

## Verbinden von Objekten

::: column-margin
Join mittels {{< kbd Ctrl >}} + {{< kbd J >}}
:::

Mehrere Objekte lassen sich auch verbinden, sodass sie zu einem Objekt werden. Hierfür müssen die zu verbindenden Objekte markiert werden. Die Verbindung der Objekte erfolgt anschliessend mittels der Tastenkombination {{< kbd Ctrl >}} + {{< kbd J >}} . Wichtig ist dabei, dass eines der markierten Objekte das aktive Objekt darstellt. Üblicherweise handelt es sich dabei um das zuletzt ausgewählte Objekt. Das aktive Objekt ist jeweils anhand einer orangen statt einer roten Markierung ersichtlich. Die anderen Objekte werden anschliessend zum aktiven Objekt hinzugefügt. Wenn mehrere Objekte ausgewählt sind, allerdings kein Objekt der Auswahl das aktive Objekt darstellt, wird das Verbinden von Objekten nicht durchgeführt.

## Verstecken von Objekten

::: column-margin
Verstecken von Objekten mittels {{< kbd H >}}
:::

Gerade bei sehr komplexen Szenen kann es vorkommen, dass sich die Objekte gegenseitig verdecken und die Bearbeitung etwas schwieriger wird. In diesem Falle gibt es die Möglichkeit, Objekte in der Ansicht zu verstecken. Ausgewählte Objekte können mittels der Taste versteckt werden. Im Outliner sind die Objekte nach wie vor noch angegeben, allerdings grau hinterlegt. Mittels der Tastenkombination {{< kbd Alt >}} + {{< kbd H >}} werden alle versteckten Objekte wieder angezeigt. Mittels der Tastenkombination {{< kbd Shift >}} + {{< kbd H >}} lassen sich zudem alle Objekte, ausser den ausgewählten Objekten, verstecken. Dadurch sind nur noch die markierten Objekte sichtbar.

:::::: tippbox
:::: tippbox-header
::: tippbox-icon
:::
Weiterführende Informationen
::::

::: tippbox-body
Statt Objekte in einer Szene zu verstecken kann alternativ auch die lokale Ansicht mittels der Taste {{< kbd / >}} auf diese Objekte angewendet werden. In dieser Ansicht werden alle anderen Objekte ausgeblendet. Um wieder in die normale Ansicht zu gelangen, muss erneut die Taste {{< kbd / >}} gedrückt werden.
:::
::::::

::: column-margin
Versteckte Objekte im Outliner aufdecken
:::

Um einzelne Objekte wieder anzeigen zu lassen, kann im Outliner das geschlossene Auge neben dem entsprechenden Objekt angewählt werden. Analog kann auch ein geöffnetes Auge angewählt werden, um die Objekte zu verstecken. Das Verstecken von Objekten bezieht sich nur auf den Viewport-Display. In einem finalen Render werden die Objekte trotzdem gerendert und sind dementsprechend sichtbar.

## Anordnen in Collections

::: column-margin
Collections
:::

Im Outliner lassen sich die verschiedenen Objekte in Collections anordnen. Hierfür werden die Objekte jeweils in eine Collection hineingezogen. Anschliessend werden die Objekte innerhalb dieser Collection aufgelistet. Auch andere Collections können in eine Collection hineingezogen werden. Somit können mithilfe der Collections Ordnerstrukturen im Outliner erstellt werden. Dies ermöglicht, dass die Objekte innerhalb einer Collection als gemeinsame Gruppe für komplexere Vorhaben verwendet werden können – etwa für Partikel-Effekte.

::: column-margin
Hinzufügen und Deaktivieren von Collections
:::

Mithilfe der Schaltfläche oben rechts in der Ecke des Outliners können neue Collections hinzugefügt werden. Hierfür muss je nach Bildschirmgrösse allenfalls der Header des Outliners nach rechts gescrollt oder der Outliner vergrössert werden. Mittelt dem Kontrollkästchen neben einer Collection lassen sich die Objekte innerhalb einer Collection deaktivieren. Die entsprechenden Objekte werden anschliessend im Viewport nicht mehr angezeigt und auch beim Rendern nicht mehr berücksichtig.

## Speichern

::: column-margin
Zwischenspeichern mittels {{< kbd Ctrl >}} + {{< kbd S >}} ist unabdingbar
:::

Bisher wurden bereits einige Tastenkombinationen angesprochen. Die wichtigste Tastenkombination stellt allerdings die Kombination für das Abspeichern des aktuellen Projekts dar: {{< kbd Ctrl >}} + {{< kbd S >}}. Zwischenspeichern ist bei der Arbeit mit Blender eine wichtige Empfehlung. Je nach Komplexität des Projektes kann es manchmal vorkommen, dass das Programm unerwartet abstürzt und die Fortschritte bis zum letzten Speicherpunkt verloren gehen. Aus diesem Grund empfiehlt es sich, das Projekt lieber einmal zu viel als einmal zu wenig abzuspeichern.

::: column-margin
Kopie speichern
:::

Alternativ kann das Projekt auch unter «*File* \| *Save*» abgespeichert werden. Nebst der Möglichkeit, dass ein Projekt unter einem neuen Namen gespeichert und fortgeführt wird («*File* \| *Save* as» bzw. {{< kbd Ctrl >}} + {{< kbd Shift >}} + {{< kbd S >}}), gibt es auch die Möglichkeit, mittels «*File* \| *Save Copy*» ({{< kbd Ctrl >}} + {{< kbd Alt >}} + {{< kbd S >}}) eine Backup-Version abzuspeichern und in dem originalen File weiterzuarbeiten.

::: column-margin
.blend-Files
:::

Die Projekte werden jeweils in Blenders programmeigenem Format «*.blend*» abgespeichert. Diese Datei enthält alle Objekte, Animationen und Einstellungen des Projektes. Das .blend-Dateiformat kann lediglich mit Blender geöffnet werden. Wenn externe Dateien (beispielsweise Texturen, Soundeffekte oder Videos) im Projekt eingebunden werden, müssen diese ebenfalls mit dem Projekt weitergegeben werden. Es gibt jedoch die Möglichkeit, unter «*File* \| *External Data* \| *Pack all into.blend*» alle diese externen Dateien in das .blend-File einzuspeichern. Dadurch erhöht sich allerdings die Grösse des abgespeicherten Files.

::: column-margin
Exportieren
:::

Um Programme auch für andere Projekte verfügbar zu machen, müssen sie in einem anderen Dateiformat ausgegeben werden. Unter «*File* \| *Export*» steht eine Reihe von verschiedenen Dateiformaten zur Verfügung, welche von unterschiedlichen Programmen geöffnet werden können. Die meisten dieser Dateiformate kann Blender wiederum importieren und darstellen.

:::::: rememberbox
:::: rememberbox-header
::: rememberbox-icon
:::

Merke...
::::

::: rememberbox-body
Lieber einmal mehr mit der Kombination {{< kbd Ctrl >}} + {{< kbd S >}}, speichern, als die Fortschritte zu verlieren.
:::
::::::
